### ISSUE TITLE
Issues with warnings on Ruby 2.3

### ISSUE THREAD

**Issue by Quesar** [djberg96/html-table#1]
When using html-table-1.4.2 with Ruby 2.3 and adding just require 'html/table' the execution of my gem fails with:
```
/Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/html-table-1.4.2/lib/html/table.rb:8:in `<top (required)>': superclass must be a Class (Module given) (TypeError)
	from /Users/username/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/username/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/username/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/my-reporter-0.3.0/lib/my-reporter/reporter.rb:1:in `<top (required)>'
```

This happens because of these warnings:
```
# Warning raised if a non-standard extension is used.
class NonStandardExtensionWarning < Warning; end

# Please, think of the children before using the blink tag.
class BlinkWarning < Warning; end
```

**Comment by djberg96** [comment]
I'm guessing this is actually Ruby 2.4, which added their own Warning module, which conflicts with older versions of the structured_warnings gem. Try installing the latest version of structured_warnings (0.3.x) and see if the error goes away.

In the meantime, I'll update the dependency and push out a new gem soon.

**Comment by djberg96** [comment]
Oops, disregard last comment. I need to update the warning class names to accomdate the changes in 0.3.x.

**Comment by djberg96** [comment]
Ok, updated the gem and pushed out html-table 1.5.0. Please use that. :)

**Comment by Quesar** [comment]
The new version (1.5.0) seems to be working. Thank you. :)
