### ISSUE TITLE
Does it not surport Chinese？

### ISSUE THREAD

**Issue by LONGDDSF** [djberg96/html-table#12]
I create a row, and set the content to an array
```
row.content = ['错误类型',"错误位置"]
```
but,the html file appears garbled.

**Comment by djberg96** [comment]
Hi @LONGDDSF, I ran this test locally on my Mac and it worked fine:

ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]

```
table = Table.new{ |t|
  t.content = [
    %w[hello world],
    %w['错误类型',"错误位置"]
  ]
}

puts table.html

File.open("temp.txt", "w"){ |fh| fh.puts table.html }
```

Both the console output and the file contents seem to be ok. I ran this on a Mac terminal, which defaults to UTF-8 as far as I know.

What version of Ruby are you using? Which operating system? And what's your local encoding? What did you view the file with?

**Comment by LONGDDSF** [comment]
So sorry, I am a little busy recently.
The Ruby using is 2.4.1,and macOS 10.15.4.
I have soled this problem,many thanks!

**Comment by djberg96** [comment]
@LONGDDSF May I ask what the problem was?

**Comment by djberg96** [comment]
Anyway, I'll close for now, but feel free to add a followup.
