### ISSUE TITLE
I cannot get this gem to work, I get an error from the require statement

### ISSUE THREAD

**Issue by Stephendkruger** [djberg96/html-table#2]
So, I install the gem using Bundler Install, and put in the require statement, and it kicks this error:

ruby TriageReport.rb 
/Library/Ruby/Gems/2.0.0/gems/html-table-1.4.2/lib/html/table.rb:8:in `<top (required)>': superclass must be a Class (Module given) (TypeError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from TriageReport.rb:5:in `<main>'

**Comment by djberg96** [comment]
@Stephendkruger The first thing you'll want to do is install a newer version of Ruby. That version looks like the version that came with OSX, and it is quite old. Do `brew install ruby`. Once you've got that setup, install the latest version of html-table, which is currently at 1.5.0.

**Comment by Stephendkruger** [comment]
I had hoped I could get it to work with 2.0. the wired thing is, even when
I pinned older version of your gem it still failed
Anyway, apologies I should have tried against newest Ruby. I just hoped I
could use the version from several years ago. I am handcuffed to 2.0

**Comment by djberg96** [comment]
@Stephendkruger Have you tried updating to html-table 1.5.0? There was an update with *structured_warnings* that should resolve that error.

**Comment by Stephendkruger** [comment]
I tried every version, one after the other, it just seems unhappy in Ruby 2.0

**Comment by djberg96** [comment]
@Stephendkruger Sorry to hear it. There's nothing I can do I'm afraid.

**Comment by Stephendkruger** [comment]
Hey, no worries. You are amazing for trying. Thanks for making a cool gem.
The only thing I world suggest is adding version dependencies to the gem
page with which version of Ruby is required.

Have an awesome week!
