### ISSUE TITLE
structured_warnings gem having codebase-wide impact

### ISSUE THREAD

**Issue by dansteele** [djberg96/html-table#8]
Getting some test failures throughout my application because the structured_warnings gem is getting angry for some reason. It's also causing issues in a third-party gem buttercms [on this line](https://github.com/ButterCMS/buttercms-ruby/blob/master/lib/buttercms-ruby.rb#L74). Not sure why.

It's always 
```bash
     TypeError:
       wrong argument type Hash (expected String)
```

I've worked around the issue in our codebase, but don't want to start modifying other gems 😓 
I think that #5 was meant to prevent this, but unsure.

**Comment by dansteele** [comment]
It's because I was requiring the gem. Note to Rails users - use `require: false`.

🦆

**Comment by djberg96** [comment]
Hm, wonder what you ran into exactly. Anyway, glad you got it worked out!
